import os


_POSTGRES_USER = os.environ.get('POSTGRES_USER')
_POSTGRES_PASSWORD = os.environ.get('POSTGRES_PASSWORD')
_POSTGRES_HOST = os.environ.get('POSTGRES_HOST')
_POSTGRES_PORT = int(os.environ.get('POSTGRES_PORT', 5432))
_POSTGRES_DB_NAME = os.environ.get('POSTGRES_DB')

_SQLALCHEMY_DATABASE_URI = f"postgresql://{_POSTGRES_USER}:{_POSTGRES_PASSWORD}" \
                           f"@{_POSTGRES_HOST}:{_POSTGRES_PORT}/{_POSTGRES_DB_NAME}"

SETTINGS = {
    'SQLALCHEMY_DATABASE_URI': _SQLALCHEMY_DATABASE_URI,
    'SQLALCHEMY_TRACK_MODIFICATIONS': False,
    'POSTGRES_USER': _POSTGRES_USER,
    'POSTGRES_PASSWORD': _POSTGRES_PASSWORD,
    'POSTGRES_HOST': _POSTGRES_HOST,
    'POSTGRES_PORT': _POSTGRES_PORT,
    'POSTGRES_DB_NAME': _POSTGRES_DB_NAME,
    'SECRET_KEY': 'secretkey',
}
